trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: BakeryOSSFeedCredentials
  - name: CACHE
    value: ~/.cache

steps:
  - task: CacheBeta@1
    displayName: Ivy cache
    inputs:
      key: 'cache'
      path: '$(CACHE)'

  - task: Bash@3
    displayName: Generate artifacts' version
    inputs:
      targetType: 'inline'
      script: bash ./set-version.sh

  - task: Bash@3
    displayName: 'Prepare publishing credentials'
    inputs:
      targetType: 'inline'
      script: printf "realm=pkgs.dev.azure.com\nhost=pkgs.dev.azure.com\nuser=${FEEDUSER}\npassword=${FEEDPASSWORD}\n" > ~/.credentials
    env:
      FEEDPASSWORD: $(feedPassword)

  - script: sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} package #clean coverage test coverageReport
    displayName: 'Running sbt'

  - script: du -h ~
    displayName: 'Disk use'

  - script: sbt aetherDeploy
    displayName: 'Publishing results'
    condition: succeeded()
