trigger:
  - master
  - feature*

pool:
  vmImage: 'ubuntu-latest'

variables:
  IVY_HOME: $(Pipeline.Workspace)/.ivy2

steps:
  - task: CacheBeta@1
    inputs:
      key: 'ivy'
      path: '$(IVY_HOME)'
      displayName: Ivy build cache

  - script: sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} clean coverage test coverageReport
    displayName: 'Running sbt'
