trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: BakeryOSSFeedCredentials
  - name: IVY_HOME
    value: $(Pipeline.Workspace)/.ivy2

steps:
  - task: CacheBeta@1
    displayName: Ivy cache
    inputs:
      key: 'ivy'
      path: '$(IVY_HOME)'

  - task: Bash@3
    displayName: Generate artifacts' version
    inputs:
      targetType: 'inline'
      script: bash ./set-version.sh

  - script: printf "realm=BakeryOSSFeed\\nhost=${feedUrl}\\nuser=${feedUser}\\npassword=${feedPassword}\n" > ~/.credentials
        cat ~/.credentials
    displayName: 'Update credentials'

  - script: sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} package #clean coverage test coverageReport
    displayName: 'Running sbt'

  - script: du -h ~
    displayName: 'Disk use'

  - script: sbt publish
    displayName: 'Publishing results'
    condition: succeeded()